### ISSUE TITLE
Meaning of the colored temperature pill on the Home screen

### ISSUE THREAD

**Issue by serrq** [davidtakac/bura#10]
Strength bar. I didn't understand properly its use. The white dot?

![1000108575](https://github.com/davidtakac/bura/assets/113377431/7ca5ad0e-db6c-43a4-b8dc-26ee68077645)

**Comment by davidtakac** [comment]
First, the strength bar:

1. The temperatures on the left and right are the minimum and maximum temperatures of the day, respectively
2. If you look at all of the days in your screenshot, you can see that Thu has the coldest day, and Today has the warmest day
3. The "strength bar" is therefore the temperature range of the day relative to the temperature range of the entire week

The white dot represents the temperature right now. It is only present for the "Today" day.

**Comment by serrq** [comment]
Can we close this issue as solved?

**Comment by davidtakac** [comment]
Sure, closing it now 👍
