### ISSUE TITLE
feature req: refresh update rate, manual update only

### ISSUE THREAD

**Issue by nutpantz** [davidtakac/bura#15]
While many people have huge internet plans done people have very limited ones. A user setting for update refresh rate would be great.
Myself i only need one update a Day.
And really only need a manual update for each location.
My internet plan is 5gb a year, so you can see why it matters a lot to me.

**Comment by serrq** [comment]
This is also the case of foreign data plans while traveling.

**Comment by davidtakac** [comment]
I didn't expect people wanting *longer* refresh periods. That makes sense 👍

**Comment by nutpantz** [comment]
Each location refresh separately or all option maybe. Not sure how that would work unless refresh was manual for viewed location only, or a update all button.

**Comment by serrq** [comment]
Yes. A manual refresh button for each location in "roaming" mode. It seems a data plan saver solution.

**Comment by davidtakac** [comment]
I did some calculations: 

Every open-meteo request uses about 3.6 kB of data. A request is made only if the cache is older than 1 hour. If we assume a user views the forecast every waking hour of the day, 365 days a year, the total data spent would be: 

3.6 kB * 18h * 365 = 23652 kB ≈ 23.6 MB

This is the most wasteful scenario. Even in your plan of only 5GB per year, this scenario uses only 0.46% of it. Realistically, people will pull new data 3-4 times a day, and the rest would fall into the cache period. 

And in roaming, people either turn off their data or buy a local temporary SIM card. 

For these reasons, this will remain as not planned. Thank you for the discussion.
