### ISSUE TITLE
Pure black theme

### ISSUE THREAD

**Issue by Donkey-Doug** [davidtakac/bura#2]
I am personally missing a pure black theme option.

**Comment by davidtakac** [comment]
Hey Doug, thanks for the feedback. Would pure black mean all the surfaces that are now shades of grey would be the same color (pure black)? I fear that might  make the app harder to read, because different levels of tonal elevation help organize the information and make it scannable.

**Comment by pagusupu** [comment]
I think just having the background colour/darkest tone pure black would work well enough while keeping everything readable, having themes like this is great on devices with oled panels

**Comment by davidtakac** [comment]
Thank you for the suggestion and discussion, but this is not planned at the moment.
