### ISSUE TITLE
Crash at startup - Samsung S9+

### ISSUE THREAD

**Issue by HonkyTronky** [davidtakac/bura#22]
Version 1.0.3 and 1.0.2 crash as soon as app is launched

Samsung S9+ with Android 10 abd Samsung UI 2.5

*Gimme instructions where to find crash logs to upload for analysis*

regards

**Comment by davidtakac** [comment]
Did you try clearing your app data? See #7. I had to change the local storage schema to fix the issue, which is why updates crash.

**Comment by HonkyTronky** [comment]
You got it ! Now it works like a charm ....

Thank you !

Maurizio 

Il 4 Aprile 2024 20:43:46 UTC, "David Takač" ***@***.***> ha scritto:
