### ISSUE TITLE
Why norten says its a potencil Malware

### ISSUE THREAD

**Issue by Stzyxh** [davidtakac/bura#23]
Since update it says that

**Comment by davidtakac** [comment]
No idea. Maybe because it's not an app from the Play Store? Does it say the reason?

**Comment by Stzyxh** [comment]
No i have a lot of apps that are not in the play store.

**Comment by davidtakac** [comment]
Hmm, I honestly have no clue. Does Norton specify reasons for flagging an app as malware? 

That being said, the update only fixed some UI bugs. The app is not malware, but don't take my word for it. Feel free to read through the code and see for yourself.

**Comment by Stzyxh** [comment]
Norton says the app is suspicious, but another app available in the play store norten says it is malware but the norten app advisor says the app is safe. a bit weird.

**Comment by davidtakac** [comment]
Weird, yes. I don't know how Norton determines this, therefore I have no way of fixing it.

**Comment by serrq** [comment]
The developer should contacting Norton team to find a solution (in my opinion).

**Comment by Stzyxh** [comment]
Since  1.05 no Malware anymore. Bruh
