### ISSUE TITLE
Temperature graphs on the main screen are not coherent with temperature graphs in detailed pages

### ISSUE THREAD

**Issue by stemy2** [davidtakac/bura#27]
Some example to illustrate.

![Screenshot_20240409-075230_Bura](https://github.com/davidtakac/bura/assets/22192600/d9fa9f67-c3ce-4c36-ac22-b1d43f5140c1)
As you can see, the temperature graphs on lines of wednesday and saturday are highly different.

But if you look at the detailed pages, you see that the graph have both a min temp at 4.30 - 5.00 AM with a max temp at 4.00 PM.

![Screenshot_20240409-075852_Bura](https://github.com/davidtakac/bura/assets/22192600/060ecafa-5bba-4f94-a0a7-ef777db2a5e2)

![Screenshot_20240409-075932_Bura](https://github.com/davidtakac/bura/assets/22192600/2b704e45-75a5-43ff-96ce-227e68a612c0)

How is it possible ?

**Comment by davidtakac** [comment]
Hi, if I understood correctly, you would expect Wednesday to have its max. temp somewhere near the start of the day because its temperature bar is all the way to the left? If so, this is not how the temp bar works. For more details, see #10

**Comment by stemy2** [comment]
Not really. In my mind, according temperature bars, wednesday temperatures should be at their lowest at the beginning of the day and at their highest at approx. 12.00 PM, and for saturday, the temps should rise not before 12.00 PM and until the end of the day.

**Comment by davidtakac** [comment]
Ah, so the weather data itself does not seem right? Have you tried comparing with another app or provider? Bura only displays what it gets from Open-Meteo, but of course there might be a bug.

**Comment by davidtakac** [comment]
Ohh I see what you mean now. The position of the coloured bar inside the overall bar does not correspond to time of day. You can see the FAQ section of the readme, I added an explanation of it there: 

> The extreme ends of the spectrum are the full temperature range of the week. The colored bar is the temperature range for that day, and the dot is the current temperature.
