### ISSUE TITLE
Explain the bar on each day

### ISSUE THREAD

**Issue by LeftyDextrous** [davidtakac/bura#28]
Perhaps I am stupid, but it has only just occurred to me what the gradient colored bar to the right of the daily weather forecast on the home screen indicates.

I may be wrong, but for those who have not figured it out, the extreme ends of the spectrum are the full temperature range of the week. The colored bar is the temperature range for that day, and the dot is the current temperature. 

With that said, I think it would be helpful for there to be an explanation for that particular UI element somewhere, whether on the Github page, the settings menu (as a "? Help" button), or evennas an introductory tutorial on first launch.

**Comment by davidtakac** [comment]
You are not stupid, a couple other people asked the same thing 😄 I admit it is not very intuitive at first. I like your explanation because it is simple and clear. I'll create an FAQ section in the README and paste it there.

**Comment by LeftyDextrous** [comment]
Cool, glad I could help!

Apr 10, 2024 08:18:08 David Takač ***@***.***>:

**Comment by davidtakac** [comment]
Your explanation is now in the README, thanks!

**Comment by LeftyDextrous** [comment]
Yo that's really neat

Apr 18, 2024 05:01:46 David Takač ***@***.***>:
