### ISSUE TITLE
Fastlane issues

### ISSUE THREAD

**Issue by IzzySoft** [davidtakac/bura#3]
There are some minor issues with your fastlane structure:

* `phoneScreenshots` must be one level deeper (`images/phoneScreenshots`)
* `images/icon.png` is missing
* `full_description.txt` lacks an empty line before the bullet-point list to render properly as Markdown

Could you please fix that? Thanks in advance!

**Comment by davidtakac** [comment]
Hey, thank you for bringing this to my attention. I pushed a fix right now. How does it look?

**Comment by IzzySoft** [comment]
Excellent, thanks!

![image](https://github.com/davidtakac/bura/assets/6781438/2d6c5943-f6a5-4213-992d-47cad5029afe)

(the description is adjusted manually by me before you fixed `full_description.txt`, so the app name is in italics. If you wish, you can use simple HTML formatting (italics, bold etc), which is supported by all parties I know using Fastlane – so including my repo (where the screenshot is from), F-Droid and PlayStore)

That said, your app will [become available in my repo](https://apt.izzysoft.de/packages/com.davidtakac.bura/) with the next sync around 7 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme :smiley:

**Comment by davidtakac** [comment]
Looks great, thanks! It's available in the repo, I'll add the badge :)

**Comment by IzzySoft** [comment]
Yes, it is available there now – and I already [announced it](https://floss.social/@IzzyOnDroid/112186184131406448) and also added your app to the [corresponding listing](https://android.izzysoft.de/applists/category/named/various_weatherapps) on my Android website :smiley: So go ahead and pick one of the badges, or shields, that suits you best :wink:

**Comment by davidtakac** [comment]
Awesome, thank you for the shout-out! :smile:

**Comment by IzzySoft** [comment]
And thanks to you for adding the badge :star_struck:
