### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ngocanhtve** [davidtakac/bura#30]
Why block translations on weblate?

**Comment by davidtakac** [comment]
I've applied for their libre hosting program and they advise blocking contributions until it gets granted. As soon as that happens, I will unblock them.

**Comment by ngocanhtve** [comment]
How about PR? I will translate using PR!

**Comment by davidtakac** [comment]
Sure! That would be great.

**Comment by ngocanhtve** [comment]
You have merged my translation pull request, this issue is considered resolved, I will close the  issue.
