### ISSUE TITLE
All network requests seem to fail

### ISSUE THREAD

**Issue by freijon** [davidtakac/bura#37]
I have this app installed since about a week. Everything worked well until a few days ago when suddenly `bura` wasn't able to display the weather reliably anymore. There was a black "Loading screen" indicating the information is loading in the background, but it never completed. When killing the app and trying again and again, it sometimes managed to load the screen, but rarely.

I then reset the app completely, which also removed my locations. Now I can't even add new locations, `bura` tells me

> You seem to be offline. Connect to the Internet and try again.

But I'm clearly online, other apps work as intended. Is there maybe some API key involved that exceeded its limit?

**Comment by davidtakac** [comment]
What you're describing does look like throttling from Open-Meteo. Although I doubt you managed to exceed 10 000 requests in such a short time. 

Can you tell me the locations for which this was happening and your app version? The fact that it sometimes managed to load the data is weird.

Also, can you try going to app info and clearing storage (this is different from uninstalling) and see if that solves the issue?

**Comment by freijon** [comment]
> Can you tell me the locations for which this was happening and your app version? The fact that it sometimes managed to load the data is weird.

If this helps you find the root cause I can send you the location privately, I don't want to let everyone on the web know my location ;) The version is 1.2.0 (installed via Obtainium from the Github release)

> Also, can you try going to app info and clearing storage (this is different from uninstalling) and see if that solves the issue?

That's in fact what I did. Now that you mentioned it's different from uninstalling, I tried to uninstall and now it works. I was able to add my location and the weather data is loaded correctly (and fast).

Let's see how long it lasts... Is it possible that an update breaks it?

**Comment by davidtakac** [comment]
> I don't want to let everyone on the web know my location

No problem, I understand if you're uncomfortable with that :)

> Let's see how long it lasts... Is it possible that an update breaks it?

Yes. Do you remember from which version you updated? If your previous version was 1.0.1 or lower, the update required you to clear your app data. Same thing if it was below 1.1.1 and you selected a location with no sunrise or sunset for a day. 

In any case, please report back if it happens again and I can take a closer look.

**Comment by freijon** [comment]
Unfortunately the issue is back:
![Screenshot_20240423-215128_Bura_1](https://github.com/davidtakac/bura/assets/1387831/2980ab15-e553-4c04-94b6-43e2f36210c2)

> Do you remember from which version you updated?

It must have been 1.1.1, I just recently installed the app

**Comment by davidtakac** [comment]
Ah, okay, let's take a closer look. Would you mind sending me the location for which this happens in an e-mail? You can find my e-mail address on my GitHub profile.

**Comment by freijon** [comment]
> In your screenshot on GitHub, I see an unusual Android status bar. Are you running an alternative OS? Have you manually set your phone's time?

I'm using e/OS 1.21.1-s-20240325389527-stable-avicii (Android 12). I did not set the time manually.

**Comment by davidtakac** [comment]
I see e/OS has an "Advanced privacy" feature that hides your IP address and apparently [causes issues with Internet speed for some users](https://community.e.foundation/t/very-slow-internet-speed-on-fairphone-3-with-eos/42003/2). Could you turn it off and try again?

**Comment by freijon** [comment]
It's already off. Also, other apps using Openweather, e.g. Breezy, work fine

**Comment by davidtakac** [comment]
Ah, okay. Do they also take a while to load but finish normally? I see I've set relatively short network timeouts of 5 seconds. Maybe your requests are exceeding this limit and failing prematurely.

**Comment by freijon** [comment]
No, it loads instantly. Also with `bura` (when it works) it loads instantly.

**Comment by davidtakac** [comment]
That's pretty weird. Does the app remain stuck on the loading screen from the screenshot you posted forever?

**Comment by freijon** [comment]
Yes, it will never recover and stay like this forever, there is no error message. If I try to add a new location, it will show:

> You seem to be offline. Connect to the Internet and try again.

**Comment by davidtakac** [comment]
> other apps using Openweather, e.g. Breezy, work fine

Bura uses Open-Meteo, not Openweather. Can you try setting Breezy to use Open-Meteo and see if you get the same issue?

**Comment by davidtakac** [comment]
1.4.0 is out now with network timeouts increased to 10s. It's a stretch, but does it help by any chance?

**Comment by freijon** [comment]
It's been working the past few days. I'll keep an eye on it.

**Comment by davidtakac** [comment]
Hey, I assume this is no longer happening. I'll close the issue as completed. Feel free to reopen otherwise.
