### ISSUE TITLE
F-Droid: Shorter changelog required

### ISSUE THREAD

**Issue by offa** [davidtakac/bura#40]
I'm working on the [F-Droid packaging](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14974), but got a failure because of 

> whatsNew in en-US should be shorter than 500 characters!

I guess it's because the recent release has a bit too much text in the fastlane changelog. Another release where the [entry is < 500 chars](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure) should work.

Otherwise the build looks good so far :+1:.

**Comment by davidtakac** [comment]
Thanks for bringing this to my attention, I wasn't aware of this restriction. Is it enough if I edit the latest changelog file, or do I need to create an entirely new release?

**Comment by offa** [comment]
> Thanks for bringing this to my attention, I wasn't aware of this restriction.

Me neither :grin:.

The safest might be a new release if possible.

**Comment by davidtakac** [comment]
Alright, I'll do that and update this thread when a new release is available. Could be a couple days, work ramped up recently.

**Comment by davidtakac** [comment]
@offa 1.3.0 (version code 10) is out now and its changelog 10.txt has < 500 chars.

**Comment by offa** [comment]
Thank you, update of the packaging PR is on the way.
