### ISSUE TITLE
[request] more wind information

### ISSUE THREAD

**Issue by ralencode** [davidtakac/bura#44]
now, there only is an informationi about current wind. and the arrow points in a wrong direction (not to where the wind blows, but from where). i would like to see daily (and hourly) wind forecast too

**Comment by davidtakac** [comment]
> the arrow points in a wrong direction (not to where the wind blows, but from where)

You're right! Will fix ASAP. 

> daily (and hourly) wind forecast too

Planned right after UV index graphs (see the README for list of planned features)

Thanks!
