### ISSUE TITLE
Bura on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [davidtakac/bura#54]
Hey David Takač,

I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have Bura listed in the repo. Please review the listing at https://www.openapk.net/bura/com.davidtakac.bura/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by davidtakac** [comment]
Hey there, thanks for including the app in your repository. That is completely OK with me.
