### ISSUE TITLE
New release for translations

### ISSUE THREAD

**Issue by ltguillaume** [davidtakac/bura#60]
I see that development has stagnated a bit, no worries, but I thought I'd ask if you'd be willing to do a quick release for inclusion of the translation PRs.

**Comment by davidtakac** [comment]
Yeah, work ramped up these past few months. I'll make a build with the translations, sure! Thank you for the reminder (and the PR) 😄

**Comment by ltguillaume** [comment]
Thanks, much appreciated! 😃

**Comment by davidtakac** [comment]
1.6.0 is out now with Dutch and Spanish added, and Polish fixed.

**Comment by ltguillaume** [comment]
Thanks! 😃
